id = "rust-snippets"
name = "Rust Snippets"
version = "0.0.1"
schema_version = 1
authors = ["Bobby Mannino <manninobobby@icloud.com>"]
description = "Rust snippets for the Zed IDE. A collection of Rust snippets to improve your development speed."
repository = "https://github.com/bobbymannino/rust-snippets-for-zed"
snippets = "./snippets/rust.json"
